spring:
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    initialization-mode: always
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user
    username: postgres
    password: admin

server:
  port: 10002
    
eureka:
  client:
    service-url: 
        defaultZone: http://localhost:10000/eureka

aws:
  region: ap-southeast-1
  bucket-name: user-service-s3-bucket

local:
  users:
    file:
      path: s3-files