spring:
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    initialization-mode: always
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/book
    username: postgres
    password: admin

server:
  ort: 10001
    
eureka:
  client:
    service-url: 
        defaultZone: http://localhost:10000/eureka
      